export interface Wilaya {
  code: string;
  nameEn: string;
  nameAr: string;
  communes: string[];
}

export const ALGERIA_WILAYAS: Wilaya[] = [
  { code: "01", nameEn: "01 - Adrar", nameAr: "01 - أدرار", communes: ["Adrar", "Reggane", "Timimoun", "Aoulef", "Tsabit"] },
  { code: "02", nameEn: "02 - Chlef", nameAr: "02 - الشلف", communes: ["Chlef", "Ténès", "Ténès", "Boukadir", "Oued Fodda", "El Karimia"] },
  { code: "03", nameEn: "03 - Laghouat", nameAr: "03 - الأغواط", communes: ["Laghouat", "Aflou", "Hassi R'Mel", "Ksar El Hirane"] },
  { code: "04", nameEn: "04 - Oum El Bouaghi", nameAr: "04 - أم البواقي", communes: ["Oum El Bouaghi", "Aïn Beïda", "Aïn M'lila", "Aïn Kercha"] },
  { code: "05", nameEn: "05 - Batna", nameAr: "05 - باتنة", communes: ["Batna", "Barika", "Aïn Touta", "Arris", "Merouana"] },
  { code: "06", nameEn: "06 - Béjaïa", nameAr: "06 - بجاية", communes: ["Béjaïa", "Amizour", "Akbou", "El Kseur", "Seddouk"] },
  { code: "07", nameEn: "07 - Biskra", nameAr: "07 - بسكرة", communes: ["Biskra", "Tolga", "Sidi Okba", "Ouled Djellal", "Zeribet El Oued"] },
  { code: "08", nameEn: "08 - Béchar", nameAr: "08 - بشار", communes: ["Béchar", "Kenadsa", "Abadla", "Béni Abbès"] },
  { code: "09", nameEn: "09 - Blida", nameAr: "09 - البليدة", communes: ["Blida", "Boufarik", "El Affroun", "Ouled Yaïch", "Mouzaïa", "Beni Mered"] },
  { code: "10", nameEn: "10 - Bouira", nameAr: "10 - البويرة", communes: ["Bouira", "Lakhdaria", "Sour El Ghozlane", "Aïn Bessem"] },
  { code: "11", nameEn: "11 - Tamanrasset", nameAr: "11 - تمنراست", communes: ["Tamanrasset", "In Salah", "Abalessa", "In Guezzam"] },
  { code: "12", nameEn: "12 - Tébessa", nameAr: "12 - تبسة", communes: ["Tébessa", "Cheria", "Bir El Ater", "El Aouinet"] },
  { code: "13", nameEn: "13 - Tlemcen", nameAr: "13 - تلمسان", communes: ["Tlemcen", "Mansourah", "Maghnia", "Remchi", "Ghazaouet", "Chetouane"] },
  { code: "14", nameEn: "14 - Tiaret", nameAr: "14 - تيارت", communes: ["Tiaret", "Sougueur", "Frenda", "Ksar Chellala"] },
  { code: "15", nameEn: "15 - Tizi Ouzou", nameAr: "15 - تيزي وزو", communes: ["Tizi Ouzou", "Draâ Ben Khedda", "Azazga", "Boghni", "Larbaâ Nath Irathen", "Tigzirt"] },
  { code: "16", nameEn: "16 - Alger", nameAr: "16 - الجزائر العاصمة", communes: ["Alger Centre", "Sidi M'Hamed", "El Biar", "Bab El Oued", "Hydra", "Kouba", "Babra", "Cheraga", "Dely Ibrahim", "Zeralda", "Hussein Dey", "Bachdjerrah", "Ain Taya", "Bordj El Kiffan", "Bordj El Bahri", "Saoula", "Draria", "Souidania", "Douera", "Birtouta", "Baraki"] },
  { code: "17", nameEn: "17 - Djelfa", nameAr: "17 - الجلفة", communes: ["Djelfa", "Aïn Oussera", "Messaad", "Hassi Bahbah"] },
  { code: "18", nameEn: "18 - Jijel", nameAr: "18 - جيجل", communes: ["Jijel", "Taza", "El Milia", "Sidi Abdelaziz", "Taher"] },
  { code: "19", nameEn: "19 - Sétif", nameAr: "19 - سطيف", communes: ["Sétif", "El Eulma", "Aïn Arnat", "Aïn Oulmene", "Bougaa"] },
  { code: "20", nameEn: "20 - Saïda", nameAr: "20 - سعيدة", communes: ["Saïda", "Youb", "Aïn El Hadjar"] },
  { code: "21", nameEn: "21 - Skikda", nameAr: "21 - سكيكدة", communes: ["Skikda", "El Harrouch", "Collo", "Azzaba"] },
  { code: "22", nameEn: "22 - Sidi Bel Abbès", nameAr: "22 - سيدي بلعباس", communes: ["Sidi Bel Abbès", "Télagh", "Sfisef", "Ben Badis"] },
  { code: "23", nameEn: "23 - Annaba", nameAr: "23 - عنابة", communes: ["Annaba", "El Bouni", "Berrahal", "El Hadjar", "Seraïdi"] },
  { code: "24", nameEn: "24 - Guelma", nameAr: "24 - قالمة", communes: ["Guelma", "Oued Zenati", "Bouchegouf", "Héliopolis"] },
  { code: "25", nameEn: "25 - Constantine", nameAr: "25 - قسنطينة", communes: ["Constantine", "El Khroub", "Hamma Bouziane", "Didouche Mourad", "Zighoud Youcef"] },
  { code: "26", nameEn: "26 - Médéa", nameAr: "26 - المدية", communes: ["Médéa", "Berrouaghia", "Ksar El Boukhari", "Ouzera"] },
  { code: "27", nameEn: "27 - Mostaganem", nameAr: "27 - مستغانم", communes: ["Mostaganem", "Aïn Tedles", "Sidi Ali", "Bouguerat"] },
  { code: "28", nameEn: "28 - M'Sila", nameAr: "28 - المسيلة", communes: ["M'Sila", "Boussaâda", "Sidi Aïssa", "M'Tarfa"] },
  { code: "29", nameEn: "29 - Mascara", nameAr: "29 - معسكر", communes: ["Mascara", "Sig", "Tighennif", "Mohammadia"] },
  { code: "30", nameEn: "30 - Ouargla", nameAr: "30 - ورقلة", communes: ["Ouargla", "Hassi Messaoud", "Touggourt", "N'Goussa"] },
  { code: "31", nameEn: "31 - Oran", nameAr: "31 - وهران", communes: ["Oran", "Es Sénia", "Bir El Djir", "Aïn El Turk", "Arzew", "Béthioua", "Mers El Kébir", "Boutlelis"] },
  { code: "32", nameEn: "32 - El Bayadh", nameAr: "32 - البيض", communes: ["El Bayadh", "Brezina", "El Abiodh Sidi Cheikh"] },
  { code: "33", nameEn: "33 - Illizi", nameAr: "33 - إليزي", communes: ["Illizi", "Djanet", "In Amenas"] },
  { code: "34", nameEn: "34 - Bordj Bou Arréridj", nameAr: "34 - برج بوعريريج", communes: ["Bordj Bou Arréridj", "Ras El Ma", "Bordj Ghdir", "El Achir"] },
  { code: "35", nameEn: "35 - Boumerdès", nameAr: "35 - بومرداس", communes: ["Boumerdès", "Bordj Menaïel", "Dellys", "Khemis El Khechna", "Hammedi", "Naciria"] },
  { code: "36", nameEn: "36 - El Tarf", nameAr: "36 - الطارف", communes: ["El Tarf", "El Kala", "Ben M'Hidi", "Bouteldja"] },
  { code: "37", nameEn: "37 - Tindouf", nameAr: "37 - تندوف", communes: ["Tindouf", "Oum El Assel"] },
  { code: "38", nameEn: "38 - Tissemsilt", nameAr: "38 - تيسمسيلت", communes: ["Tissemsilt", "Thiet", "Bordj Bou Naama"] },
  { code: "39", nameEn: "39 - El Oued", nameAr: "39 - الوادي", communes: ["El Oued", "Robbah", "Bayadha", "Guemar"] },
  { code: "40", nameEn: "40 - Khenchela", nameAr: "40 - خنشلة", communes: ["Khenchela", "Kais", "Chechar", "El Hamma"] },
  { code: "41", nameEn: "41 - Souk Ahras", nameAr: "41 - سوق أهراس", communes: ["Souk Ahras", "Sedrata", "Mdaourouch"] },
  { code: "42", nameEn: "42 - Tipaza", nameAr: "42 - تيبازة", communes: ["Tipaza", "Cherchell", "Kolea", "Fouka", "Bou Ismail", "Ahmer El Aïn"] },
  { code: "43", nameEn: "43 - Mila", nameAr: "43 - ميلة", communes: ["Mila", "Chelghoum Laïd", "Tadjenanet", "Grarem Gouga"] },
  { code: "44", nameEn: "44 - Aïn Defla", nameAr: "44 - عين الدفلى", communes: ["Aïn Defla", "Khemis Miliana", "Miliana", "El Attaf"] },
  { code: "45", nameEn: "45 - Naâma", nameAr: "45 - النعامة", communes: ["Naâma", "Mecheria", "Aïn Sefra"] },
  { code: "46", nameEn: "46 - Aïn Témouchent", nameAr: "46 - عين تموشنت", communes: ["Aïn Témouchent", "Hammam Bou Hadjar", "Béni Saf"] },
  { code: "47", nameEn: "47 - Ghardaïa", nameAr: "47 - غرداية", communes: ["Ghardaïa", "El Guerrara", "Metlili", "Berriane"] },
  { code: "48", nameEn: "48 - Relizane", nameAr: "48 - غليزان", communes: ["Relizane", "Oued Rhiou", "Mazouna", "Ammi Moussa"] },
  { code: "49", nameEn: "49 - Timimoun", nameAr: "49 - تيميمون", communes: ["Timimoun", "Aougrout", "Tinerkouk"] },
  { code: "50", nameEn: "50 - Bordj Badji Mokhtar", nameAr: "50 - برج باجي مختار", communes: ["Bordj Badji Mokhtar", "Timiaouine"] },
  { code: "51", nameEn: "51 - Ouled Djellal", nameAr: "51 - أولاد جلال", communes: ["Ouled Djellal", "Sidi Khaled"] },
  { code: "52", nameEn: "52 - Béni Abbès", nameAr: "52 - بني عباس", communes: ["Béni Abbès", "Igli", "El Ouata"] },
  { code: "53", nameEn: "53 - In Salah", nameAr: "53 - عين صالح", communes: ["In Salah", "In Ghar", "Foggaret Azzaouia"] },
  { code: "54", nameEn: "54 - In Guezzam", nameAr: "54 - عين قزام", communes: ["In Guezzam", "Tin Zaouatine"] },
  { code: "55", nameEn: "55 - Touggourt", nameAr: "55 - تقرت", communes: ["Touggourt", "N'Goussa", "Megarine", "Tebesbest"] },
  { code: "56", nameEn: "56 - Djanet", nameAr: "56 - جانت", communes: ["Djanet", "Bordj El Haouas"] },
  { code: "57", nameEn: "57 - El M'Ghair", nameAr: "57 - المغير", communes: ["El M'Ghair", "Djamaa"] },
  { code: "58", nameEn: "58 - El Meniaa", nameAr: "58 - المنيعة", communes: ["El Meniaa", "Hassi Gara"] },
];
